/* glossary.js: one plain-words glossary shared by every front of the site (landing, main, archive, Advanced, terminal).
   Each entry: [title, pattern that finds the word, explanation]. Wording is educational and never advice. */
(function () {
  "use strict";
  window.BLabGlossary = [
    ["Last price", /^last$|last price|^ltp$/i, "The price of the most recent trade. Prices here are delayed about 15 minutes unless a row says live."],
    ["Change / Change %", /^chg$|^chg ?%$|^chg%$|change/i, "How far the price has moved since the previous close, in rupees and as a percentage. Green is up, red is down."],
    ["Volume", /^volume$/i, "How many shares changed hands. A big number means lots of people were trading it."],
    ["Value traded", /^value$/i, "Volume multiplied by price: the total rupees that changed hands."],
    ["Relative volume", /rel vol/i, "Today's trading compared with its usual pace. 2x means twice as busy as normal."],
    ["Sweep", /^sweep$/i, "Unusually large orders that clear several price levels in one go. Shown only when the optional local feed is running."],
    ["Delivery", /^delivery$/i, "The share of traded shares that were actually taken home instead of closed out the same day. Higher can mean longer-term holders."],
    ["52-week range", /52[- ]?w(eek)?( range| high| low)?/i, "The lowest and highest price over the past year. The bar shows where today's price sits between them."],
    ["Day's range", /day'?s range/i, "The lowest and highest price so far today."],
    ["NSE Live", /nse live/i, "Which of NSE's own live lists this price was picked up from."],
    ["P/E ratio", /^p\/e|\bp\/e\b/i, "Price divided by yearly profit per share. Roughly, how many rupees people pay today for one rupee of yearly profit."],
    ["Market cap", /market cap/i, "Share price times the number of shares: the stock market's total value of the company."],
    ["Moving average (SMA / EMA)", /\bsma\b|\bema\b|moving average|200-day|50-day|200dma/i, "The average closing price over the last N days. A price above its long average is often read as an uptrend, below as a downtrend."],
    ["RSI", /\brsi\b/i, "A 0 to 100 gauge of recent price strength. Above 70 is often called overheated and below 30 weak; it is a rule of thumb, not a forecast."],
    ["MACD", /macd/i, "Compares a fast and a slow average to show whether momentum is picking up or fading."],
    ["ADX", /\badx\b/i, "How strong a trend is, in either direction. Above about 25 is usually called a clear trend."],
    ["+DI / -DI", /\+di|-di/i, "Two lines that compare the pull upward with the pull downward in price."],
    ["Bollinger bands", /bollinger/i, "A band around the average price. Touching the edge means the price is unusually far from its normal."],
    ["Stochastic / CCI / Williams %R", /stochastic|\bcci\b|williams/i, "More momentum gauges. Each one asks whether the recent move has gone unusually far."],
    ["Momentum (12-1)", /momentum/i, "How much the price rose over the past year, leaving out the latest month. Stocks that rose tend to be compared with those that fell."],
    ["Volatility", /volatil/i, "How jumpy the price is. Higher means bigger swings up and down."],
    ["India VIX", /\bvix\b/i, "A gauge of how jumpy the market expects to be over the next month. Higher means more nervous."],
    ["FII / DII", /\bfii\b|\bdii\b|\bfpi\b/i, "Foreign (FII) and domestic (DII) institutions: the big funds. Net flows show whether they put money in or took it out."],
    ["Advancing / declining (breadth)", /adv ?\/ ?dec|advanc|declin|breadth/i, "How many stocks rose compared with how many fell. More risers than fallers means the rise is broad."],
    ["NIFTY 50 / NIFTY 500", /nifty|sensex|index/i, "An index is a basket of big listed companies used as a yardstick for the whole market. NIFTY 50 holds the 50 largest, NIFTY 500 the largest 500."],
    ["Candlestick", /candle/i, "Each candle is one period. The thick body runs from the opening to the closing price; the thin lines show the highest and lowest."],
    ["Log scale", /^log$/i, "A chart scale where equal distances mean equal percentage moves, useful for long histories."],
    ["Decile", /decile/i, "Stocks sorted into ten equal groups. Decile 1 is the model's top group, decile 10 its bottom."],
    ["P(up)", /p\(up\)|p\(down\)|chance it beats|chance/i, "The student model's estimated probability of the stated outcome. It is a statistic, not a promise, and it is often wrong."],
    ["Fundamental / Technical / Sentiment", /fundamental|technical|sentiment/i, "Three views of a stock: its company numbers (fundamental), its price history (technical) and the tone of recent news (sentiment)."],
    ["F-Score", /f-?score|piotroski/i, "A 0 to 9 health score built from nine yes/no questions about a company's annual reports."],
    ["Magic Formula (ROC and earnings yield)", /magic|\broc\b|earnings yield/i, "A published way of ranking companies on how well they use their money (return on capital) and how cheap their profit is (earnings yield)."],
    ["EPS", /\beps\b/i, "Earnings per share: the company's yearly profit divided by its number of shares."],
    ["Dividend yield", /dividend/i, "The yearly cash a company pays out per share, as a percentage of the share price."],
    ["ROE", /\broe\b/i, "Return on equity: profit as a percentage of the owners' money in the business."],
    ["Debt / equity", /debt/i, "How much the company has borrowed compared with the owners' money. Higher means more borrowing."],
    ["Confidence", /confidence/i, "How many of the model's views agree. More agreement means higher confidence, not certainty."],
    ["Watchlist", /watchlist/i, "A list of stocks you follow. Add the one on screen with the star button."],
    ["Bullish / bearish", /bullish|bearish/i, "Bullish means leaning toward rising prices; bearish means leaning toward falling prices. They describe a lean, not a certainty."],
    ["Replay", /replay/i, "Plays back a past trading day minute by minute using real prices."],
    ["Order book", /order book|ladder/i, "The live list of everyone willing to trade a stock and at what price: one side wants to pay (bids), the other wants to be paid (asks)."],
    ["Bid and ask (spread)", /\bbids?\b|\basks?\b|spread/i, "The bid is the best price someone will pay; the ask is the lowest price someone will accept. The gap between them is the spread."],
    ["Market order", /market order/i, "An order that goes through straight away at the best price available, instead of waiting at a price you choose."],
    ["SIP", /\bsip\b/i, "A systematic investment plan: putting in a fixed amount every month, whatever the price."],
    ["Compounding", /compound/i, "Growth on top of earlier growth: gains in one year start earning gains of their own in the next."],
    ["Risk and return", /risk (&|and) return|risk\/return|drawdown/i, "Return is how much you gained or lost; risk is how bumpy the ride was. A drawdown is a fall from a peak."],
    ["Diversification", /diversif/i, "Spreading money across different stocks so one bad one hurts less."],
    ["Liquidity (liquid)", /liquid/i, "How easily a stock can be traded without moving its price. Busy, large stocks are liquid."],
    ["Top gainers and losers", /gainer|loser/i, "The stocks whose prices rose the most (gainers) or fell the most (losers) in the last trading session."],
    ["NSE", /\bnse\b/i, "The National Stock Exchange of India, where these shares are traded."],
    ["Closing price", /closing price|previous close|end-of-day/i, "The price of the last trade of the day. End-of-day data is final once the exchange publishes its files."],
    ["Consensus (analysts)", /consensus|analyst/i, "The average view of the professional analysts who follow a stock. Analysts are often too optimistic."],
    ["Trend (200-day)", /trend/i, "Whether prices have mostly been rising or falling over a longer period. Price above its 200-day average is often read as an uptrend."]
  ];
})();
