"""
Keeps the ALADIN 2.0 methodology in README.md identical, word for word, to the text the ALADIN 2.0 tab shows (its "Method" page).
The single source is data/config/aladin2_method.json (the build copies it to site/aladin2/method.json).

  python scripts/make_aladin2_readme.py          rewrite the marked block in README.md
  python scripts/make_aladin2_readme.py --check  exit 1 if README.md is out of date (used by the tests)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "config" / "aladin2_method.json"
README = ROOT / "README.md"
START = "<!-- ALADIN2-METHOD:START (generated by scripts/make_aladin2_readme.py from data/config/aladin2_method.json: edit that file, not this block) -->"
END = "<!-- ALADIN2-METHOD:END -->"


def render(method):
    out = ["### ALADIN 2.0 methodology (the same text the ALADIN 2.0 tab shows)", "", f"*{method['disclaimer']}*", ""]
    for s in method["sections"]:
        out += [f"**{s['h']}**", ""]
        for p in s["p"]:
            out += [p, ""]
    out += ["**Not measured, and why**", ""] + [f"- {name}: {why}" for name, why in method["not_measured"]] + [""]
    return "\n".join(out).rstrip() + "\n"


def block(method):
    return f"{START}\n{render(method)}{END}"


def current_block(text):
    a, b = text.find(START), text.find(END)
    return None if a < 0 or b < 0 else text[a:b + len(END)]


def update(text, method):
    new = block(method); cur = current_block(text)
    if cur is not None:
        return text.replace(cur, new)
    marker = "## Design system & motion"                       # keep it next to the ALADIN 1 methodology, before the next section
    return text.replace(marker, new + "\n\n" + marker, 1) if marker in text else text.rstrip("\n") + "\n\n" + new + "\n"


def main(argv=None):
    method = json.loads(SRC.read_text(encoding="utf-8"))
    text = README.read_text(encoding="utf-8").replace("\r\n", "\n"); new = update(text, method)
    if argv and "--check" in argv:
        return 0 if new == text else 1
    README.write_text(new, encoding="utf-8"); print("README.md ALADIN 2.0 methodology block updated"); return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
