"""
Keeps the ALADIN methodology in README.md identical, word for word, to the text the ALADIN tab shows.
The single source is data/config/aladin_method.json (the tab loads it as site/aladin_method.json).

  python scripts/make_aladin_readme.py          rewrite the marked block in README.md
  python scripts/make_aladin_readme.py --check  exit 1 if README.md is out of date (used by the tests)
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "config" / "aladin_method.json"
README = ROOT / "README.md"
START, END = "<!-- ALADIN-METHOD:START (generated by scripts/make_aladin_readme.py from data/config/aladin_method.json: edit that file, not this block) -->", "<!-- ALADIN-METHOD:END -->"


def render(method):
    out = ["### ALADIN methodology (the same text the ALADIN tab shows)", "", f"*{method['disclaimer']}*", ""]
    for s in method["sections"]:
        out += [f"**{s['h']}**", ""]
        for p in s["p"]:
            out += [p, ""]
    out += ["**Not measured, and why**", ""] + [f"- {name}: {why}" for name, why in method["not_measured"]] + [""]
    return "\n".join(out).rstrip() + "\n"


def block(method):
    return f"{START}\n{render(method)}{END}"


def current_block(text):
    a, b = text.find(START), text.find(END)
    return None if a < 0 or b < 0 else text[a:b + len(END)]


def update(text, method):
    new = block(method)
    cur = current_block(text)
    if cur is not None:
        return text.replace(cur, new)
    return text.rstrip("\n") + "\n\n" + new + "\n"


def main(argv=None):
    method = json.loads(SRC.read_text(encoding="utf-8"))
    text = README.read_text(encoding="utf-8").replace("\r\n", "\n")
    new = update(text, method)
    if argv and "--check" in argv:
        return 0 if new == text else 1
    README.write_text(new, encoding="utf-8")
    print("README.md ALADIN methodology block updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
